server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&nullCatalogMeansCurrent=true&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    rest:
      uris: http://localhost:9200
      username: elasticsearch

  static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}

mybatis-plus:
  mapper-locations: classpath:mapping/**/*Mapping.xml
  type-aliases-package: com.snow.learn.entity

#showSql
logging:
  level:
    com:
      snow:
        learn:
          mapper: debug